spring:
  profiles:
    active: dev
  sql:
    init:
      mode: always

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:~/dev-shopping-cart;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
